name: Flutter

on: 
  push:
    branches: [master]
    paths: 
      - lib/**
      -  .github/workflows/flutter.yml


jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}   
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}   
        channel: 'beta' # or: 'dev' or 'beta'
    - run: flutter packages get
    - run: flutter pub run build_runner build
    - run: flutter build web
    - run: cp -fR build/web/* firebase/public
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: name-of-the-project
